-- Supabase 데이터베이스 테이블 생성 및 스토리지 보안 정책 설정을 위한 SQL 코드

-- 센서 데이터 및 사진 로그 저장용 테이블 생성
CREATE TABLE sensor_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    device_id TEXT,
    temperature FLOAT,      -- 온도 1 
    temperature2 FLOAT,     -- 온도 2 
    humidity FLOAT,         -- 습도
    co2_level FLOAT,        -- CO2 농도
    image_url TEXT         -- Supabase 스토리지 이미지 경로
);

-- 스토리지 보안 정책 설정
-- 라즈베리파이에서 촬영한 사진을 Supabase의 스토리지에 업로드 할 수 있도록 허용
CREATE POLICY "누구나 업로드 가능" 
ON storage.objects FOR INSERT 
TO public 
WITH CHECK (bucket_id = 'plant_images');

-- 라즈베리파이에서 데이터베이스에  데이터를 보낼 수 있도록 보안 검사를 일시적으로 해제
ALTER TABLE public.sensor_logs DISABLE ROW LEVEL SECURITY;
